name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Check directory structure
        run: |
          echo "Repository root contents:"
          ls -la
          echo "Looking for Next.js files:"
          find . -name "package.json" -type f
          find . -name "next.config.*" -type f
          echo "All directories:"
          find . -type d -maxdepth 2

      - name: Install dependencies
        run: |
          echo "Current directory: $(pwd)"
          cd finex-website
          echo "Changed to finex-website directory: $(pwd)"
          echo "Package.json contents:"
          cat package.json
          npm ci

      - name: Build Next.js app
        run: |
          echo "Current directory: $(pwd)"
          cd finex-website
          echo "Changed to finex-website directory: $(pwd)"
          echo "Running npm run build..."
          npm run build 2>&1 | tee build.log
          echo "Build completed with exit code: $?"
          if [ -d "out" ]; then
            echo "Output directory created successfully"
            ls -la out/
          else
            echo "ERROR: Output directory not created"
            echo "Build log:"
            cat build.log
          fi
        env:
          NODE_ENV: production

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: finex-website/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4